#!/usr/bin/env perl

use strict; 
#use warnings FATAL => 'all';
use warnings;
use Test::More; 
use Data::Dumper;
use File::Slurp ':all';

my $JDIR = $ENV{JDIR};

require_ok('App::NetdiscoX::Util::ACI');

my $aci = App::NetdiscoX::Util::ACI->new(
      host => "dummy.local",
);


my $fvCEp = slurp($JDIR."/fvCEp_1.json");
my $topSystem = slurp($JDIR."/topSystem_1.json");
my $aggr = slurp($JDIR."/aggr_1.json");
my $info = $aci->read_info_from_json($fvCEp, $topSystem, $aggr);

# check eth codepath
my @r1 = grep { $_->{node} =~ m/AA:BB:CC:ED:52:E5/i }@{$info->{node_ips}};
is (@r1, 3, "node_ip number of test entries");
ok ( (grep { $_->{ip} =~ m/185.37.204.26/i } @r1), "canary IP eth found");

# check vpc codepath
my @r2 = grep { $_->{node} =~ m/AA:BB:CC:1C:DE:71/i } @{$info->{node_ips}};
is (@r2, 2, "node_ip number of test entries");
ok ( (grep { $_->{ip} =~ m/34.230.36.52/i } @r2), "canary IP vpc found");


done_testing;
