#!/usr/bin/env perl

use strict; 
use warnings;
use Test::More; 
use Data::Dumper;
use File::Slurp ':all';

my $JDIR = $ENV{JDIR};

require_ok('App::NetdiscoX::Util::ACI');

my $aci = App::NetdiscoX::Util::ACI->new(
      host => "dummy.local",
);


my $fvCEp = slurp($JDIR."/fvCEp_2.json");
my $topSystem = slurp($JDIR."/topSystem_2.json");
my $aggr = slurp($JDIR."/aggr_2.json");
my $info = $aci->read_info_from_json($fvCEp, $topSystem, $aggr);


# check simple eth 
my @ethrec = grep { $_->{port} =~ m/eth/i }@{$info->{nodes}};
is (@ethrec, 90, "nodes number of eth entries");
ok ($ethrec[5]->{mac}, "nodes->mac exists");
is ($ethrec[5]->{port}, "Ethernet1/39", "port longification eth - Ethernet");

# check vpc aggregated entries
my @porec = grep { $_->{port} =~ m/port-channel/i }@{$info->{nodes}};
is (@porec, 4346, "nodes number of po entries");
my @vpc_canaries = grep { $_->{port} eq "port-channel1" 
    && $_->{mac} eq "BE:EF:E7:59:01:FD"} @porec;
is (@vpc_canaries, 6, "nodes number of checked vpc entries");


done_testing;
