#!/usr/bin/env perl

use strict; 
#use warnings FATAL => 'all';
use warnings;
use Test::More; 
use Data::Dumper;
use File::Slurp ':all';

my $JDIR = $ENV{JDIR};

require_ok('App::NetdiscoX::Util::ACI');

my $aci = App::NetdiscoX::Util::ACI->new(
      host => "dummy.local",
);


my $fvCEp = slurp($JDIR."/fvCEp_2.json");
my $topSystem = slurp($JDIR."/topSystem_2.json");
my $aggr = slurp($JDIR."/aggr_2.json");
my $info = $aci->read_info_from_json($fvCEp, $topSystem, $aggr);

# check vpc codepath
my @r1 = grep { $_->{node} =~ m/BE:EF:6F:BC:84:0F/i }@{$info->{node_ips}};
is (@r1, 2, "node_ip number of test entries");
ok ( (grep { $_->{ip} =~ m/202.35.191.6/i } @r1), "canary IP eth found");

done_testing;
